### Exercici 1

#### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [ ]:
import numpy as np

array_1D = np.array([1,6,9,14,85])
array_2D = np.array([[1,3,9],[10,12,14]])

def resum_st(nparray):
    print("Resum estadístic de l'array:\n", nparray)
    if nparray.ndim > 1:
        print("error: només es poden introduïr arrays d'1 dimensió")
    else:
        print("valor màxim de l'array:", np.amax(nparray))
        print("valor mínim de l'array:", np.amin(nparray))
        print("valor mediana de l'array:", np.median(nparray))
        print("valor mig de l'array:", np.mean(nparray))
        print("valor mitjana de l'array:", np.average(nparray))
        print("valor desviació estándar de l'array:", np.std(nparray))
        print("valor variança de l'array:", np.var(nparray))
        print("valor coeficient correlació de l'array:", np.corrcoef(nparray))
        print("fi de l'estudi estadístic\n")
       
resum_st(array_1D)
resum_st(array_2D)

### Exercici 2

#### Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [ ]:
from numpy import random

print("Introdueix valor N de la matriu quadrada:")
N = int(input())

def quadrat(N):
    array_q = random.randint(100, size=(N, N))
    print (array_q)

quadrat(N)

### Exercici 3

#### Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [10]:
import numpy as np

array1_2D = np.array([[1,3,9],[10,12,14]])
array2_2D = np.array([[6,7,8,3,4,5],[88,76,55,13,44,90]])


def suma(nparray):
    print('\n')
    print("suma de filas y columnas de la matriz:\n", nparray)
    print("que tiene filas:",nparray.shape[0]) #devuelve número de filas
    print("y columnas:", nparray.shape[1]) #devuelve número de columnas
    
    i1 = 0
    sum_f = 0
    while i1 < nparray.shape[1]: #mientras sea inferior al número de columnas
        sum_f = nparray[:,i1] + sum_f #suma cada elemento de la fila
        i1 += 1
    
    i2 = 0 #algoritmo para imprimir el resultado por filas
    while i2 < nparray.shape[0]: 
        print("la suma de fila",i2+1, "es:",sum_f[i2])    
        i2 += 1
    
    j1 = 0
    sum_c = 0
    while j1 < nparray.shape[0]: #mientras sea inferior al número de filas
        sum_c = nparray[j1,:] + sum_c #suma cada elemento de la columna
        j1 += 1

    j2 = 0 #algoritmo para imprimir el resultado por columnas
    while j2 < nparray.shape[1]: 
        print("la suma de columna",j2+1, "es:",sum_c[j2])    
        j2 += 1
  

suma(array1_2D)
suma(array2_2D)



suma de filas y columnas de la matriz:
 [[ 1  3  9]
 [10 12 14]]
que tiene filas: 2
y columnas: 3
la suma de fila 1 es: 13
la suma de fila 2 es: 36
la suma de columna 1 es: 11
la suma de columna 2 es: 15
la suma de columna 3 es: 23


suma de filas y columnas de la matriz:
 [[ 6  7  8  3  4  5]
 [88 76 55 13 44 90]]
que tiene filas: 2
y columnas: 6
la suma de fila 1 es: 33
la suma de fila 2 es: 366
la suma de columna 1 es: 94
la suma de columna 2 es: 83
la suma de columna 3 es: 63
la suma de columna 4 es: 16
la suma de columna 5 es: 48
la suma de columna 6 es: 95


### Exercici 4

#### Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [12]:
import numpy as np
import math

array1_2D = np.array([[2,4,6],[4,6,8]])
array2_2D = np.array([[6,7,8,3,4,5],[88,76,55,13,44,90]])

def coef_corr(nparray):
  
    nf1_av = np.average(nparray[0,:]) #calculo valor medio fila 1
    nf2_av = np.average(nparray[1,:]) #calculo valor medio fila 2
    
    nf1_dif = nparray[0,:] - nf1_av #a cada elemento de fila 1 se le resta el valor medio
    nf2_dif = nparray[1,:] - nf2_av #a cada elemento de fila 2 se le resta el valor medio
    
    nf1_2 = nf1_dif**2 #el resultado de la resta a potencia 2
    nf2_2 = nf2_dif**2 #el resultado de la resta a potencia 2
    
    nf12 = nf1_dif * nf2_dif #se multiplican las diferencias de cada elemento de cada fila
    
    a = np.sum(nf12) #sumatorio de los valores
    b = math.sqrt(np.sum(nf1_2)) #sumatorio de los valores y raiz cuadrada
    c = math.sqrt(np.sum(nf2_2)) #sumatorio de los valores y raiz cuadrada
  
    corr = a / (b*c)
    print(corr)

    
print("el coeficient de correlació de la matriu:\n", array1_2D)
print("segons la formula implementada és:")  
coef_corr(array1_2D)
print("segons la formula de numpy és:") 
print(np.corrcoef(array1_2D))
print("\n")
print("el coeficient de correlació de la matriu:\n", array2_2D)    
print("segons la formula implementada és:")  
coef_corr(array2_2D)
print("segons la formula de numpy és:") 
print(np.corrcoef(array2_2D))



el coeficient de correlació de la matriu:
 [[2 4 6]
 [4 6 8]]
segons la formula implementada és:
0.9999999999999998
segons la formula de numpy és:
[[1. 1.]
 [1. 1.]]


el coeficient de correlació de la matriu:
 [[ 6  7  8  3  4  5]
 [88 76 55 13 44 90]]
segons la formula implementada és:
0.5462821430346243
segons la formula de numpy és:
[[1.         0.54628214]
 [0.54628214 1.        ]]
